#ifndef RESOURCES_H_INCLUDED
#define RESOURCES_H_INCLUDED

#define IDR_FONT_REGULAR 101
#define IDR_FONT_BOLD    102

#define IDI_ICON1        201
#define IDI_ICON_STEER   202

#define IDR_IMGUI_CONFIG 301

#endif
